name: hornblastersadmin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core:
  cloud_firestore:
  get_storage:
  path: ^1.8.0
  path_provider: ^2.0.8
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  firebase_storage:
  flutter_launcher_icons: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon2.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon2.png"


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AlternateGot
      fonts:
        - asset: assets/fonts/AlternateGotNo3D.ttf
    - family: GaleanaCondensed
      fonts:
        - asset: assets/fonts/GaleanaCondensed-HeavyIt.otf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
